# ğŸ”— Links:
# Source file: https://github.com/obytes/react-native-template-obytes/blob/master/.github/workflows/lint-ts.yml

# âœï¸ Description:
# This action is used to run eslint checks
# Runs on pull requests and pushes to the main/master branches
# Based on the event type:
#   - If it's a pull request, it will run eslint, then add the check to the PR as well as annotate the code with the errors and warnings.
#   - If it's a push to main/master, it will run the type checking and fail if there are any errors.

# ğŸš¨ GITHUB SECRETS REQUIRED: NONE

name: Lint TS (eslint)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: Lint TS (eslint)
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ“¦ Setup Node + NPM + install deps
        uses: ./.github/actions/setup-node-npm-install

      - name: ğŸƒâ€â™‚ï¸ Run ESLint
        run: npm run lint
        continue-on-error: true

